# Generated by Django 4.1.4 on 2022-12-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='TaskStatus',
        ),
    ]
